### ISSUE TITLE
first attempt at exporting bugs thwarted with AttributeError

### ISSUE THREAD

**Issue by ghost** [termie/lp2gh#1]
[rejon@slowtop:~/Software/lp2gh]
$ bin/lp2gh-export-bugs worldlabel > ../bugs.json
fetching Bug #812563 in worldlabel: "there isn't a clear test site setup"
Traceback (most recent call last):
  File "bin/lp2gh-export-bugs", line 27, in <module>
    o = bugs.export(FLAGS.project)
  File "/home/rejon/Software/lp2gh/lp2gh/bugs.py", line 138, in export
    rv = bug_task_to_dict(x)
  File "/home/rejon/Software/lp2gh/lp2gh/bugs.py", line 86, in bug_task_to_dict
    'date_created': util.to_timestamp(bug_task.date_created),
  File "/home/rejon/Software/lp2gh/lp2gh/util.py", line 6, in to_timestamp
    tt = (dt.year, dt.month, dt.day,
AttributeError: 'unicode' object has no attribute 'year'

**Comment by ghost** [comment]
I added a quick fix in you util.py:

import time

GH_DATE_FORMAT = '%Y-%m-%dT%H:%M:%SZ'

def to_timestamp(dt):
  fmttime = ''
  try:
        tt = (dt.year, dt.month, dt.day,
              dt.hour, dt.minute, dt.second,
              dt.weekday(), 0, 0)
        fmttime = dt.strftime(GH_DATE_FORMAT)
  except AttributeError:
        pass
  return fmttime
