### ISSUE TITLE
getting a new error on trying to import bugs

### ISSUE THREAD

**Issue by ghost** [termie/lp2gh#2]
create issue Internet Exlorer and Images
with params: {'body': u'All the images are completely different in IE including the top nav bar  (actually top bar looks cool in IE)', 'labels': ['Critical', 'Invalid'], 'title': u'Internet Exlorer and Images'}
exception: {"message":"Validation Failed","errors":[{"value":[],"code":"missing","resource":"Label","field":"name"}]}
Traceback (most recent call last):
  File "/home/rejon/Software/lp2gh/bin/lp2gh-import-bugs", line 30, in <module>
    o = bugs.import_(repo, data, milestones_map=milestones_map)
  File "/home/rejon/Software/lp2gh/lp2gh/bugs.py", line 195, in import_
    rv = issues.append(*_params)
  File "/home/rejon/Software/lp2gh/github3/client.py", line 70, in append
    rv = self.client.post(self.url, *_kw)
  File "/home/rejon/Software/lp2gh/github3/request.py", line 41, in post
    return self._opener.open(req)
  File "/usr/lib64/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 438, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 372, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422: Unprocessable Entity

**Comment by ghost** [comment]
I changed the exception block near line 195 of bugs.py from raise to pass to get around the url exception for now. Its better to get rough bugs in rather than no bugs in ;)
